[package]
name = "ecs-editor"
version = "1.0.0"
description = "ESEngine Editor - Cross-platform desktop editor"
authors = ["yhh"]
edition = "2021"

[lib]
name = "ecs_editor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-updater = "2"
tauri-plugin-http = "2"
tauri-plugin-cli = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
glob = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21"
futures-util = "0.3"
chrono = "0.4"
zip = "0.6"
base64 = "0.22"
tiny_http = "0.12"
once_cell = "1.19"
urlencoding = "2.1"
qrcode = "0.14"
image = "0.25"
notify = "7.0"
notify-debouncer-mini = "0.5"
regex = "1"
thiserror = "1"
egui = "0.27"
csscolorparser = "0.6"
egui_extras = { version = "0.27", features = ["svg"] }
eframe = { version = "0.27", default-features = true, features = ["wgpu", "glow"] }
rfd = "0.14"
open = "5"
wry = "0.47"
tao = "0.30"
raw-window-handle = "0.6"

[[bin]]
name = "egui-editor"
path = "src/bin/egui_editor.rs"

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
